// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: imageCrop.proto

package ProtoClasses

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Answer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image   []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	Ok      bool   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Answer) Reset() {
	*x = Answer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imageCrop_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_imageCrop_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_imageCrop_proto_rawDescGZIP(), []int{0}
}

func (x *Answer) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Answer) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Answer) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X uint32 `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y uint32 `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imageCrop_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_imageCrop_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_imageCrop_proto_rawDescGZIP(), []int{1}
}

func (x *Point) GetX() uint32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() uint32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type Crop struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Image       []byte `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	TopLeft     *Point `protobuf:"bytes,2,opt,name=topLeft,proto3" json:"topLeft,omitempty"`
	BottomRight *Point `protobuf:"bytes,3,opt,name=bottomRight,proto3" json:"bottomRight,omitempty"`
}

func (x *Crop) Reset() {
	*x = Crop{}
	if protoimpl.UnsafeEnabled {
		mi := &file_imageCrop_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Crop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Crop) ProtoMessage() {}

func (x *Crop) ProtoReflect() protoreflect.Message {
	mi := &file_imageCrop_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Crop.ProtoReflect.Descriptor instead.
func (*Crop) Descriptor() ([]byte, []int) {
	return file_imageCrop_proto_rawDescGZIP(), []int{2}
}

func (x *Crop) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Crop) GetTopLeft() *Point {
	if x != nil {
		return x.TopLeft
	}
	return nil
}

func (x *Crop) GetBottomRight() *Point {
	if x != nil {
		return x.BottomRight
	}
	return nil
}

var File_imageCrop_proto protoreflect.FileDescriptor

var file_imageCrop_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x43, 0x72, 0x6f, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x48, 0x0a, 0x06, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f,
	0x6b, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x23, 0x0a, 0x05, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x79,
	0x22, 0x68, 0x0a, 0x04, 0x43, 0x72, 0x6f, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x20,
	0x0a, 0x07, 0x74, 0x6f, 0x70, 0x4c, 0x65, 0x66, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x06, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x07, 0x74, 0x6f, 0x70, 0x4c, 0x65, 0x66, 0x74,
	0x12, 0x28, 0x0a, 0x0b, 0x62, 0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x52, 0x69, 0x67, 0x68, 0x74, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0b, 0x62,
	0x6f, 0x74, 0x74, 0x6f, 0x6d, 0x52, 0x69, 0x67, 0x68, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_imageCrop_proto_rawDescOnce sync.Once
	file_imageCrop_proto_rawDescData = file_imageCrop_proto_rawDesc
)

func file_imageCrop_proto_rawDescGZIP() []byte {
	file_imageCrop_proto_rawDescOnce.Do(func() {
		file_imageCrop_proto_rawDescData = protoimpl.X.CompressGZIP(file_imageCrop_proto_rawDescData)
	})
	return file_imageCrop_proto_rawDescData
}

var file_imageCrop_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_imageCrop_proto_goTypes = []interface{}{
	(*Answer)(nil), // 0: Answer
	(*Point)(nil),  // 1: Point
	(*Crop)(nil),   // 2: Crop
}
var file_imageCrop_proto_depIdxs = []int32{
	1, // 0: Crop.topLeft:type_name -> Point
	1, // 1: Crop.bottomRight:type_name -> Point
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_imageCrop_proto_init() }
func file_imageCrop_proto_init() {
	if File_imageCrop_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_imageCrop_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Answer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imageCrop_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_imageCrop_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Crop); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_imageCrop_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_imageCrop_proto_goTypes,
		DependencyIndexes: file_imageCrop_proto_depIdxs,
		MessageInfos:      file_imageCrop_proto_msgTypes,
	}.Build()
	File_imageCrop_proto = out.File
	file_imageCrop_proto_rawDesc = nil
	file_imageCrop_proto_goTypes = nil
	file_imageCrop_proto_depIdxs = nil
}
